version: '3.8'

services:
  notifications-db:
    image: postgres:14
    container_name: notifications-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifications_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - notifications_pgdata:/var/lib/postgresql/data

  notifications-app:
    build:
      context: .
    container_name: notifications-app
    depends_on:
      - notifications-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-db:5432/notifications_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  notifications_pgdata:
